export const fakeResponse = [
    {
        "url": "https://api.github.com/repos/myapos/testing_repo/issues/9",
        "repository_url": "https://api.github.com/repos/myapos/testing_repo",
        "labels_url": "https://api.github.com/repos/myapos/testing_repo/issues/9/labels{/name}",
        "comments_url": "https://api.github.com/repos/myapos/testing_repo/issues/9/comments",
        "events_url": "https://api.github.com/repos/myapos/testing_repo/issues/9/events",
        "html_url": "https://github.com/myapos/testing_repo/issues/9",
        "id": 743917859,
        "node_id": "MDU6SXNzdWU3NDM5MTc4NTk=",
        "number": 9,
        "title": "Issue created John",
        "user": {
            "login": "iotheo",
            "id": 22287199,
            "node_id": "MDQ6VXNlcjIyMjg3MTk5",
            "avatar_url": "https://avatars3.githubusercontent.com/u/22287199?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/iotheo",
            "html_url": "https://github.com/iotheo",
            "followers_url": "https://api.github.com/users/iotheo/followers",
            "following_url": "https://api.github.com/users/iotheo/following{/other_user}",
            "gists_url": "https://api.github.com/users/iotheo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/iotheo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/iotheo/subscriptions",
            "organizations_url": "https://api.github.com/users/iotheo/orgs",
            "repos_url": "https://api.github.com/users/iotheo/repos",
            "events_url": "https://api.github.com/users/iotheo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/iotheo/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-11-16T15:14:30Z",
        "updated_at": "2020-11-16T15:14:30Z",
        "closed_at": null,
        "author_association": "COLLABORATOR",
        "active_lock_reason": null,
        "body": "testing",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/myapos/testing_repo/issues/8",
        "repository_url": "https://api.github.com/repos/myapos/testing_repo",
        "labels_url": "https://api.github.com/repos/myapos/testing_repo/issues/8/labels{/name}",
        "comments_url": "https://api.github.com/repos/myapos/testing_repo/issues/8/comments",
        "events_url": "https://api.github.com/repos/myapos/testing_repo/issues/8/events",
        "html_url": "https://github.com/myapos/testing_repo/issues/8",
        "id": 743311462,
        "node_id": "MDU6SXNzdWU3NDMzMTE0NjI=",
        "number": 8,
        "title": "Issue created with API and postman V2",
        "user": {
            "login": "myapos",
            "id": 6097052,
            "node_id": "MDQ6VXNlcjYwOTcwNTI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/6097052?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myapos",
            "html_url": "https://github.com/myapos",
            "followers_url": "https://api.github.com/users/myapos/followers",
            "following_url": "https://api.github.com/users/myapos/following{/other_user}",
            "gists_url": "https://api.github.com/users/myapos/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myapos/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myapos/subscriptions",
            "organizations_url": "https://api.github.com/users/myapos/orgs",
            "repos_url": "https://api.github.com/users/myapos/repos",
            "events_url": "https://api.github.com/users/myapos/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myapos/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-11-15T18:09:45Z",
        "updated_at": "2020-11-15T18:09:45Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "Dummy body V2",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/myapos/testing_repo/issues/6",
        "repository_url": "https://api.github.com/repos/myapos/testing_repo",
        "labels_url": "https://api.github.com/repos/myapos/testing_repo/issues/6/labels{/name}",
        "comments_url": "https://api.github.com/repos/myapos/testing_repo/issues/6/comments",
        "events_url": "https://api.github.com/repos/myapos/testing_repo/issues/6/events",
        "html_url": "https://github.com/myapos/testing_repo/issues/6",
        "id": 743309217,
        "node_id": "MDU6SXNzdWU3NDMzMDkyMTc=",
        "number": 6,
        "title": "New logo v2",
        "user": {
            "login": "myapos",
            "id": 6097052,
            "node_id": "MDQ6VXNlcjYwOTcwNTI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/6097052?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myapos",
            "html_url": "https://github.com/myapos",
            "followers_url": "https://api.github.com/users/myapos/followers",
            "following_url": "https://api.github.com/users/myapos/following{/other_user}",
            "gists_url": "https://api.github.com/users/myapos/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myapos/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myapos/subscriptions",
            "organizations_url": "https://api.github.com/users/myapos/orgs",
            "repos_url": "https://api.github.com/users/myapos/repos",
            "events_url": "https://api.github.com/users/myapos/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myapos/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-11-15T17:57:43Z",
        "updated_at": "2020-11-15T17:57:43Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "We should have one",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/myapos/testing_repo/issues/5",
        "repository_url": "https://api.github.com/repos/myapos/testing_repo",
        "labels_url": "https://api.github.com/repos/myapos/testing_repo/issues/5/labels{/name}",
        "comments_url": "https://api.github.com/repos/myapos/testing_repo/issues/5/comments",
        "events_url": "https://api.github.com/repos/myapos/testing_repo/issues/5/events",
        "html_url": "https://github.com/myapos/testing_repo/issues/5",
        "id": 743298251,
        "node_id": "MDU6SXNzdWU3NDMyOTgyNTE=",
        "number": 5,
        "title": "Issue created with API",
        "user": {
            "login": "myapos",
            "id": 6097052,
            "node_id": "MDQ6VXNlcjYwOTcwNTI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/6097052?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myapos",
            "html_url": "https://github.com/myapos",
            "followers_url": "https://api.github.com/users/myapos/followers",
            "following_url": "https://api.github.com/users/myapos/following{/other_user}",
            "gists_url": "https://api.github.com/users/myapos/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myapos/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myapos/subscriptions",
            "organizations_url": "https://api.github.com/users/myapos/orgs",
            "repos_url": "https://api.github.com/users/myapos/repos",
            "events_url": "https://api.github.com/users/myapos/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myapos/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [
            {
                "id": 2507580017,
                "node_id": "MDU6TGFiZWwyNTA3NTgwMDE3",
                "url": "https://api.github.com/repos/myapos/testing_repo/labels/design",
                "name": "design",
                "color": "ededed",
                "default": false,
                "description": null
            }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-11-15T17:00:55Z",
        "updated_at": "2020-11-15T17:00:55Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "Test description",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/myapos/testing_repo/issues/4",
        "repository_url": "https://api.github.com/repos/myapos/testing_repo",
        "labels_url": "https://api.github.com/repos/myapos/testing_repo/issues/4/labels{/name}",
        "comments_url": "https://api.github.com/repos/myapos/testing_repo/issues/4/comments",
        "events_url": "https://api.github.com/repos/myapos/testing_repo/issues/4/events",
        "html_url": "https://github.com/myapos/testing_repo/issues/4",
        "id": 743297964,
        "node_id": "MDU6SXNzdWU3NDMyOTc5NjQ=",
        "number": 4,
        "title": "New logo",
        "user": {
            "login": "myapos",
            "id": 6097052,
            "node_id": "MDQ6VXNlcjYwOTcwNTI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/6097052?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myapos",
            "html_url": "https://github.com/myapos",
            "followers_url": "https://api.github.com/users/myapos/followers",
            "following_url": "https://api.github.com/users/myapos/following{/other_user}",
            "gists_url": "https://api.github.com/users/myapos/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myapos/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myapos/subscriptions",
            "organizations_url": "https://api.github.com/users/myapos/orgs",
            "repos_url": "https://api.github.com/users/myapos/repos",
            "events_url": "https://api.github.com/users/myapos/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myapos/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-11-15T16:59:25Z",
        "updated_at": "2020-11-15T16:59:25Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "We should have one",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/myapos/testing_repo/issues/3",
        "repository_url": "https://api.github.com/repos/myapos/testing_repo",
        "labels_url": "https://api.github.com/repos/myapos/testing_repo/issues/3/labels{/name}",
        "comments_url": "https://api.github.com/repos/myapos/testing_repo/issues/3/comments",
        "events_url": "https://api.github.com/repos/myapos/testing_repo/issues/3/events",
        "html_url": "https://github.com/myapos/testing_repo/issues/3",
        "id": 743268871,
        "node_id": "MDU6SXNzdWU3NDMyNjg4NzE=",
        "number": 3,
        "title": "The footer does not appear in mobile devices",
        "user": {
            "login": "myapos",
            "id": 6097052,
            "node_id": "MDQ6VXNlcjYwOTcwNTI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/6097052?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myapos",
            "html_url": "https://github.com/myapos",
            "followers_url": "https://api.github.com/users/myapos/followers",
            "following_url": "https://api.github.com/users/myapos/following{/other_user}",
            "gists_url": "https://api.github.com/users/myapos/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myapos/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myapos/subscriptions",
            "organizations_url": "https://api.github.com/users/myapos/orgs",
            "repos_url": "https://api.github.com/users/myapos/repos",
            "events_url": "https://api.github.com/users/myapos/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myapos/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-11-15T14:31:15Z",
        "updated_at": "2020-11-15T14:31:15Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "Test description for the issue 'The footer does not appear in mobile devices'",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/myapos/testing_repo/issues/2",
        "repository_url": "https://api.github.com/repos/myapos/testing_repo",
        "labels_url": "https://api.github.com/repos/myapos/testing_repo/issues/2/labels{/name}",
        "comments_url": "https://api.github.com/repos/myapos/testing_repo/issues/2/comments",
        "events_url": "https://api.github.com/repos/myapos/testing_repo/issues/2/events",
        "html_url": "https://github.com/myapos/testing_repo/issues/2",
        "id": 743268736,
        "node_id": "MDU6SXNzdWU3NDMyNjg3MzY=",
        "number": 2,
        "title": "The header is not responsive",
        "user": {
            "login": "myapos",
            "id": 6097052,
            "node_id": "MDQ6VXNlcjYwOTcwNTI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/6097052?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myapos",
            "html_url": "https://github.com/myapos",
            "followers_url": "https://api.github.com/users/myapos/followers",
            "following_url": "https://api.github.com/users/myapos/following{/other_user}",
            "gists_url": "https://api.github.com/users/myapos/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myapos/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myapos/subscriptions",
            "organizations_url": "https://api.github.com/users/myapos/orgs",
            "repos_url": "https://api.github.com/users/myapos/repos",
            "events_url": "https://api.github.com/users/myapos/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myapos/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-11-15T14:30:32Z",
        "updated_at": "2020-11-15T14:30:32Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "Test description for the issue the header is not responsive",
        "performed_via_github_app": null
    },
    {
        "url": "https://api.github.com/repos/myapos/testing_repo/issues/1",
        "repository_url": "https://api.github.com/repos/myapos/testing_repo",
        "labels_url": "https://api.github.com/repos/myapos/testing_repo/issues/1/labels{/name}",
        "comments_url": "https://api.github.com/repos/myapos/testing_repo/issues/1/comments",
        "events_url": "https://api.github.com/repos/myapos/testing_repo/issues/1/events",
        "html_url": "https://github.com/myapos/testing_repo/issues/1",
        "id": 743268621,
        "node_id": "MDU6SXNzdWU3NDMyNjg2MjE=",
        "number": 1,
        "title": "Submit is not clickable",
        "user": {
            "login": "myapos",
            "id": 6097052,
            "node_id": "MDQ6VXNlcjYwOTcwNTI=",
            "avatar_url": "https://avatars1.githubusercontent.com/u/6097052?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/myapos",
            "html_url": "https://github.com/myapos",
            "followers_url": "https://api.github.com/users/myapos/followers",
            "following_url": "https://api.github.com/users/myapos/following{/other_user}",
            "gists_url": "https://api.github.com/users/myapos/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/myapos/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/myapos/subscriptions",
            "organizations_url": "https://api.github.com/users/myapos/orgs",
            "repos_url": "https://api.github.com/users/myapos/repos",
            "events_url": "https://api.github.com/users/myapos/events{/privacy}",
            "received_events_url": "https://api.github.com/users/myapos/received_events",
            "type": "User",
            "site_admin": false
        },
        "labels": [],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [],
        "milestone": null,
        "comments": 0,
        "created_at": "2020-11-15T14:29:53Z",
        "updated_at": "2020-11-15T14:29:53Z",
        "closed_at": null,
        "author_association": "OWNER",
        "active_lock_reason": null,
        "body": "Test description for SUbmit btn not clickable",
        "performed_via_github_app": null
    }
]